<?php
/**
T4 Overide
 */

defined('_JEXEC') or die;

use Joomla\CMS\Factory;

// Create shortcuts to some parameters.
$params  = $this->item->params;

?>
<div class="com-content-article item-page<?php echo $this->pageclass_sfx; ?>">
	<meta content="<?php echo ($this->item->language === '*') ? Factory::getApplication()->get('language') : $this->item->language; ?>">

	<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
	<?php echo $this->item->event->beforeDisplayContent; ?>

	<div class="com-content-article__body">
		<?php echo $this->item->text; ?>
	</div>

	<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
	<?php echo $this->item->event->afterDisplayContent; ?>
</div>
